//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiderPlate_Cont.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public int OrderItemID { get; set; }
        public int ItemID { get; set; }
        public int Quanity { get; set; }
        public int OrderID { get; set; }
    }
}
