//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiderPlate_Cont.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int RatingID { get; set; }
        public string StarCount { get; set; }
        public int accountID { get; set; }
        public int productID { get; set; }
    
        public virtual account account { get; set; }
        public virtual product product { get; set; }
    }
}
